INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('U MARCINA', 'POLSKA', '12:00', '18:00', NULL, NULL);

INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('U STEFANA', 'POLSKA', '12:00', '18:00', NULL, NULL);

INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('U ZBYSZKA', 'POLSKA', '12:00', '18:00', NULL, NULL);