INSERT INTO ADDRESS (STREET, BUILDING_NUMBER, APARTMENT_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES ('Testowa', '10', '1', '01-010', 'TESTOWICE', 'REPUBLIKA TESTOWA');

INSERT INTO ADDRESS (STREET, BUILDING_NUMBER, APARTMENT_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES ('Wrocławska', '4', '2', '44-000', 'KATOWICE', 'POLSKA');

INSERT INTO ADDRESS (STREET, BUILDING_NUMBER, APARTMENT_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES ('Gliwicka', '10', '1', '44-000', 'KATOWICE', 'POLSKA');

INSERT INTO ADDRESS (STREET, BUILDING_NUMBER, APARTMENT_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES ('Plac Warszawski', '1', '5', '44-100', 'Zabrze', 'POLSKA');