INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID)
VALUES ('TESTEROWNIA', 'POLSKA', '10:00', '23:00', 1);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID)
VALUES ('U FRANKA', 'EUROPEJSKA', '9:00', '18:00', 2);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID)
VALUES ('DIAMENTOWA', 'WŁOSKA', '12:00', '0:00', 3);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID)
VALUES ('DA LUCA', 'WŁOSKA', '14:00', '22:30', 4);



