INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('PIEROGARNIA', 'POLSKA', '10:00', '23:00', 1, NULL);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('U FRANKA', 'EUROPEJSKA', '9:00', '18:00', 2, NULL);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('DIAMENTOWA', 'WŁOSKA', '12:00', '0:00', 3, NULL);
INSERT INTO RESTAURANT (NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES ('DA LUCA', 'WŁOSKA', '14:00', '22:30', 4, NULL);



