CREATE TABLE if not exists TABLES
(
    id BIGINT AUTO_INCREMENT,
    ARRANGEMENT VARCHAR (128) NOT NULL,
    VISIBLE_FOR_CLIENT BOOLEAN NOT NULL,
    RESTAURANT_ID BIGINT,
    foreign key (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
);