CREATE TABLE if not exists TABLES
(
    id BIGINT AUTO_INCREMENT,
    SEATS_NUMBERS BIGINT,
    VISIBLE_FOR_CLIENT BOOLEAN NOT NULL,
    RESTAURANT_ID BIGINT,
    foreign key (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
);