CREATE TABLE if not exists TABLES
(
    id BIGINT AUTO_INCREMENT,
    AVAILABILITY VARCHAR (128) NOT NULL,
    ARRANGMENT VARCHAR (128) NOT NULL,
    RESTAURANT_ID BIGINT,
    foreign key (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
);