INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');
INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');
INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');
INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');
INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');
INSERT INTO TABLES (AVAILABILITY, ARRANGMENT, RESTAURANT_ID)
VALUES (true, 'REGULAR', '1');