INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT, RESTAURANT_ID)
VALUES ('REGULAR',TRUE, 1);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT)
VALUES ('REGULAR',FALSE);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT)
VALUES ('REGULAR',TRUE);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT)
VALUES ('SQUARE',TRUE);
