INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT, RESTAURANT_ID)
VALUES ('REGULAR',TRUE, 1);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT, RESTAURANT_ID)
VALUES ('REGULAR',FALSE, 1);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT, RESTAURANT_ID)
VALUES ('REGULAR',TRUE, 1);
INSERT INTO TABLES (ARRANGEMENT, VISIBLE_FOR_CLIENT, RESTAURANT_ID)
VALUES ('SQUARE',TRUE, 1);
