INSERT INTO RATING (NAME, SURNAME, MARK, REVIEW, RESTAURANT_ID)
    VALUES ('GRZEGORZ', NULL, 4,'BARDZO DOBRA OBSŁUGA', '1');
INSERT INTO RATING (NAME, SURNAME, MARK, REVIEW, RESTAURANT_ID)
VALUES ('STEFAN', NULL, 5,'SUPER', '1');
INSERT INTO RATING (NAME, SURNAME, MARK, REVIEW, RESTAURANT_ID)
VALUES ('ELA', NULL, 2,'SUPER', '2');