INSERT INTO RESTAURANT (ID, NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES (1, 'U MARCINA', 'POLSKA', '12:00', '18:00', NULL, NULL);

INSERT INTO RESTAURANT (ID, NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES (2, 'U STEFANA', 'POLSKA', '12:00', '18:00', NULL, NULL);

INSERT INTO RESTAURANT (ID, NAME, TYPE, OPEN_HOUR, CLOSE_HOUR, ADDRESS_ID, AVG_MARK)
VALUES (3, 'U ZBYSZKA', 'POLSKA', '12:00', '18:00', NULL, NULL);